### ISSUE TITLE
Errors incorrectly flagged on description lists

### ISSUE THREAD

**Issue by denmch** [t7/trashy.css#1]
I've tried Trashy.css out on a few sites, and one thing I noticed is that it incorrectly indicates some errors on description lists.

A description list is permitted by spec to contain divs, which is a useful thing for styling discrete [term-description groups](https://www.w3.org/TR/html5/grouping-content.html#term-description-groups). E.g.,:

    <dl>
      <div>
        <dt>Foo</dt>
        <dd>Bar baz.</dd>
      </div>
      <div>
        <dt>Lorem</dt>
        <dd>Ipsum dolor sit amet.</dd>
        <dd>Also, yadda yadda yadda.</dd>
      </div>
    </dl>

Trashy.css currently flags two errors on description lists that use divs in this way:

* `<dt>` is missing a parent of `<dl>`
* Immediate child of `<dl>` must be `<dt>` or `<dd>`

The immediate child of a `<dl>` really should be either a `<div>` or a grouping of one or more `<dt>`s and `<dd>`s, but I can't imagine that's as easy to check for. But `<dd>` alone as the immediate child violates the content model.

**Comment by nathansmith** [comment]
@denmch Good catch. I appreciate this, thanks!

👍

**Comment by nathansmith** [comment]
@denmch So, that merged commit actually busted the styles.

I was able to track it down to this syntax not being supported…

```
:not(dl):not(dl > div) > dd::after,
:not(dl):not(dl > div) > dt::after {
  /* … */
}
```

Thankfully, it was an easy enough fix. This does the trick, and the styles are working again…

```
:not(dl) > div > dd::after,
:not(dl) > div > dt::after,
:not(dl):not(div) > dd::after,
:not(dl):not(div) > dt::after {
  /* … */
}
```

I also added `<div>` within `<dl>` examples to the "invalid" HTML pages…

https://t7.github.io/trashy.css/example-invalid-with-debug.html

https://t7.github.io/trashy.css/example-invalid.html
