### ISSUE TITLE
Bookmarklet needs encoding in macOS Chrome 69

### ISSUE THREAD

**Issue by pronouncedJerry** [t7/trashy.css#3]
I loaded up https://t7.github.io/trashy.css/ in Safari and was able to get it to work. I then copied the URL from the Safari Bookmarklet to Chrome and noticed that the whitespaces need to be encoded for it to work in Chrome. Anyone else have this problem?

Dragging the bookmarklet link from the page into the bookmarks bar does not work for me.

**Comment by nathansmith** [comment]
For me, dragging from the page seems to work in both Safari and Chrome.

Maybe there's some oddity about copying **from** Safari, **to** Chrome?

Regardless, I can make the link on the HTML page completely minified, without spaces.

That should fix the issue, whatever it may be. I'll get that change implemented soon.

Thanks for the heads-up!

**Comment by nathansmith** [comment]
@pronouncedJerry Okay, the link is now minified.

Let me know if this does/doesn't work for you.

Commit log here…

https://github.com/t7/trashy.css/commit/60dbbe4221604e152a28a01c67fa1181a66e2b5a

**Comment by pronouncedJerry** [comment]
that worked. thank you!
