### ISSUE TITLE
Trashy Css no longer working

### ISSUE THREAD

**Issue by robgill** [t7/trashy.css#4]
Hello I read about trashy css and saved the bookmark in September from this URL
https://css-tricks.com/introducing-trashy-css/

Recently, when I try to use it it doesn't work, is this because the name of the repo has changed? 
Or is it since updating to Chrome 70?

Here is the code I've saved in the bookmark:

```javascript:( function (d) { var f = Array.prototype.forEach; var linkTags = d.querySelectorAll('[rel=\'stylesheet\']'); var styleTags = d.querySelectorAll('style'); f.call(linkTags, function (x) { x.rel = ''; }); f.call(styleTags, function (x) { x.innerHTML = ''; }); var newLink = d.createElement('link'); newLink.rel = 'stylesheet'; newLink.href = 'https://t7.github.io/trashy.css/css/bookmarklet.css'; d.head.appendChild(newLink); } )(document);```

Thanks for the help Rob

**Comment by nathansmith** [comment]
@robgill Someone at TandemSeven didn't like the name "Trashy," so it was renamed.

The new link is here…

https://t7.github.io/construct.css/

I tried to make the case for keeping the repo name the same, to not break existing bookmarklet URLs. However, I no longer work at TandemSeven. So my advice was not heeded.

😎

NOTE: I don't fault Mundi for the name change. He was just following orders.

**Comment by robgill** [comment]
Ah so it is just the name change. 

Well thanks very much for the rapid reply! 

Great work btw! Rob

👊

NOTE: I didn't mind trashy as a name ;)
